### ISSUE TITLE
All Exercises

### ISSUE THREAD

**Issue by gabiduarte** [bbiamichelle/Assignment-Introductory-programming-exercises#1]
# Needs correction:

### [Variable and method naming](https://github.com/bbiamichelle/Assignment-Introductory-programming-exercises/blob/810df390d341990d1b26bb449d3363eaaf68289c/twuex2/src/main/java/com/thoughtworks/App.java#L13).

It is important to give your variables and methods a name that clearly has a meaning. Avoid using single letters or names other people might not understand.

### [Portuguese text](https://github.com/bbiamichelle/Assignment-Introductory-programming-exercises/blob/810df390d341990d1b26bb449d3363eaaf68289c/twuex2/src/main/java/com/thoughtworks/App.java#L10)

Since this is a TWU prep exercise, I'm expecting you to write your text (variables, methods, output sentences) in English. This will help you practice your english more ;) 

### [Main method with too much logic](https://github.com/bbiamichelle/Assignment-Introductory-programming-exercises/blob/810df390d341990d1b26bb449d3363eaaf68289c/twuex2/src/main/java/com/thoughtworks/App.java#L9)
When you implement you should extract from the main() for it's own method and only call it on main.

### Remove unused files
You have boilerplate test code on the folders and some unused App2 files. I'd want you to remove them all if you're not using.

**Comment by bbiamichelle** [comment]
Hi Gabi,

This issue is resolved.

Xoxo
